#
# Author https://fazziclay.ru/ | https://github.com/fazziclay/
#

bot_token: 'ENTER DISCORD BOT TOKEN HERE'
accounts_file_path: "./plugins/OpenDiscordAuth/accounts.json"
sessions_file_path: "./plugins/OpenDiscordAuth/sessions.json"
update_checker: true

session:
  saving_type: 0
  expired_time: 120

register_events:
  guild: 'ENTER DISCORD SERVER ID'

  add_role:
    enable: false
    obligatorily: true
    role: 'ENTER DISCORD ROLE ID'

  change_nickname:
    enable: false
    obligatorily: true
    nickname: '[] $nickname'

bungeecord:
  enable: false
  server: lobby

code_generator:
  minimum: 0
  maximum: 9999
  expired_time: 60

#code_events:
  #  hover:
  #    enable: true
  #    text: "Нажмите что бы скопировать код."
  #
  #  click:
  #    enable: true
  #    mode: 0
  #    text: "$code"

command:
  confirm: "confirm"
  cancel: "cancel"

message:
  PLUGIN_DISABLED_KICK: "Вы были отключены так как плагин был перезагружен, а вы не авторизованы."
  AUTH_TIMEOUT_KICK: "Время авторизации вышло."
  REGISTER_INSTRUCTION: "На этот аккаунт не привязан дискорд аккаунт. Для того что бы привязать аккаунт вам нужно написать полученый код в ЛС боту БОТ#0001"
  LOGIN_INSTRUCTION: "На этот ник уже привязан дискорд аккаунт. Напишите код в ЛС боту БОТ#0001"
  GIVE_CODE: "Ваш одноразовый код - $code"

  AUTHORIZATION_SUCCESSFUL: "Успешная авторизация."
  REGISTER_CANCEL: "Регистрация отменена."
  REGISTER_WARN: "Вы хотите привязать к этому нику аккаунт $discord? Напишите в чат 'confirm' для подтверждения, 'cancel' для отмены."
  REGISTER_CHECK_GAME: "Подтвердите регистрацию в игре."
  REGISTER_ADD_ROLE_MEMBER_NOT_FOUND: "Не удалось обраружить ваш дискорд аккаунт на дискорд сервере для выдачи роли."
  CODE_NOT_FOUND: "Такого кода не существует."
  CODE_USING_E1: "Данный код предназначен не для вашего дискорд аккаунта."
  CODE_GENERATOR_E1: "Извините, все возможные коды сейчас используются. Повторите попытку через минуту."