name: 'OpenDiscordAuth'
description: 'Protect your account with discord account'
version: 'Release 2.0'
main: ru.fazziclay.projects.opendiscordauth.Main
author: 'https://github.com/fazziclay'
website: 'https://github.com/fazziclay/OpenDiscordAuth/'
api-version: 1.13
load: STARTUP