name: OpenDiscordAuth
main: ru.fazziclay.opendiscordauth.Main
version: 1.8.9
website: "https://github.com/BVN4/OpenDiscordAuth/"
authors: ["https://github.com/BVN4", "https://github.com/fazziclay/", "https://github.com/TheKing-OfTime"]
load: STARTUP
api-version: 1.13

#commands:
#  o:
#    description: debug for OpenDiscordAuth
#    permission: opendiscordauth.debug
#    usage: /o
